# Generated by Django 5.0.3 on 2024-04-23 23:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenoms', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('date_embauche', models.DateTimeField(auto_now_add=True)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type_employe', models.CharField(choices=[('Guichetier', 'Guichetier'), ('Directeur Restaurant', 'Directeur Restaurant')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('capacite', models.IntegerField()),
                ('horaires_ouverture', models.TimeField()),
                ('horaires_fermeture', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('UPB', 'Université Polytechnique de Bingerville'), ('UIA', 'Institut Universitaire dAbidjan'), ('UNA', 'Université Nangui Abrogoua'), ('UFHB', 'Université Felix Houphouet Boigny')], max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('site_web', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('type_utilisateur', models.CharField(choices=[('etudiant', 'Étudiant'), ('professeur', 'Professeur'), ('adminpersonnel', 'Personnel administratif')], default='etudiant', max_length=20)),
                ('numero', models.CharField(blank=True, max_length=15)),
                ('universite', models.CharField(blank=True, choices=[('UPB', 'Université Polytechnique de Bingerville'), ('UIA', 'Institut Universitaire dAbidjan'), ('UNA', 'Université Nangui Abrogoua'), ('UFHB', 'Université Felix Houphouet Boigny')], max_length=255)),
                ('groups', models.ManyToManyField(related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Validée', 'Validée'), ('Annulée', 'Annulée')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.customuser')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=255)),
                ('filiere', models.CharField(max_length=255)),
                ('annee_etude', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=255)),
                ('date_facturation', models.DateField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mode_paiement', models.CharField(max_length=255)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Guichet',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('etat', models.CharField(choices=[('Ouvert', 'Ouvert'), ('Fermé', 'Fermé')], max_length=255)),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('Espèce', 'Espèce'), ('Wave', 'Wave')], max_length=255)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prix', models.FloatField(max_length=8)),
                ('image', models.ImageField(upload_to='')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])),
                ('commentaire', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.customuser')),
                ('plat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.plat')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='universite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.universite'),
        ),
    ]
