# Generated by Django 5.0.3 on 2024-04-08 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfoodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Validée', 'Validée'), ('Annulée', 'Annulée')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenoms', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('date_embauche', models.DateTimeField(auto_now_add=True)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type_employe', models.CharField(choices=[('Guichetier', 'Guichetier'), ('Directeur Restaurant', 'Directeur Restaurant')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenoms', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('type_utilisateur', models.CharField(choices=[('Etudiant', 'Etudiant'), ('PersonnelAdministratif', 'Personnel Administratif'), ('Enseignant', 'Enseignant')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('capacite', models.IntegerField()),
                ('horaires_ouverture', models.TimeField()),
                ('horaires_fermeture', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('UPB', 'Université Polytechnique de Bingerville'), ('UIA', 'Institut Universitaire dAbidjan'), ('UNA', 'Université Nangui Abrogoua'), ('UFHB', 'Université Felix Houphouet Boigny')], max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('site_web', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.employe')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])),
                ('commentaire', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('plat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.plat')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=255)),
                ('date_facturation', models.DateField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mode_paiement', models.CharField(max_length=255)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Guichet',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('etat', models.CharField(choices=[('Ouvert', 'Ouvert'), ('Fermé', 'Fermé')], max_length=255)),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('Espèce', 'Espèce'), ('Wave', 'Wave')], max_length=255)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='universite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.universite'),
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cfoodapp.utilisateur')),
                ('matiere', models.CharField(max_length=255)),
                ('universites', models.ManyToManyField(to='cfoodapp.universite')),
            ],
            bases=('cfoodapp.utilisateur',),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cfoodapp.utilisateur')),
                ('niveau', models.CharField(max_length=255)),
                ('filiere', models.CharField(max_length=255)),
                ('annee_etude', models.IntegerField()),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.universite')),
            ],
            bases=('cfoodapp.utilisateur',),
        ),
        migrations.AddField(
            model_name='commande',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.etudiant'),
        ),
        migrations.CreateModel(
            name='PersonnelAdministration',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cfoodapp.utilisateur')),
                ('poste', models.CharField(max_length=255)),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfoodapp.universite')),
            ],
            bases=('cfoodapp.utilisateur',),
        ),
    ]
