# Generated by Django 5.0.3 on 2024-04-19 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_user',
        ),
    ]
