# Generated by Django 5.0.3 on 2024-05-06 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfoodapp', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Panier',
        ),
        migrations.RenameModel(
            old_name='CartItem',
            new_name='PanierItem',
        ),
    ]
