# Generated by Django 5.0.3 on 2024-05-20 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfoodapp', '0003_rename_cart_panier_rename_cartitem_panieritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='directeur',
            field=models.OneToOneField(blank=True, limit_choices_to={'type_employe': 'Directeur Restaurant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfoodapp.employe'),
        ),
    ]
