# Generated by Django 5.0.3 on 2024-05-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfoodapp', '0005_remove_avis_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avis',
            old_name='date_publication',
            new_name='date_poste',
        ),
    ]
